/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as VendorsRegisterRouteImport } from './routes/vendors.register'
import { Route as DeliveryApplyRouteImport } from './routes/delivery.apply'
import { Route as DashboardVendorRouteImport } from './routes/dashboard.vendor'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardDeliveryRouteImport } from './routes/dashboard.delivery'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsRoute,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveryRoute,
} as any)
const VendorsRegisterRoute = VendorsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => VendorsRoute,
} as any)
const DeliveryApplyRoute = DeliveryApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => DeliveryRoute,
} as any)
const DashboardVendorRoute = DashboardVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveryRoute = DashboardDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delivery': typeof DeliveryRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/delivery/apply': typeof DeliveryApplyRoute
  '/vendors/register': typeof VendorsRegisterRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/delivery/apply': typeof DeliveryApplyRoute
  '/vendors/register': typeof VendorsRegisterRoute
  '/delivery': typeof DeliveryIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delivery': typeof DeliveryRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/delivery': typeof DashboardDeliveryRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/vendor': typeof DashboardVendorRoute
  '/delivery/apply': typeof DeliveryApplyRoute
  '/vendors/register': typeof VendorsRegisterRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/delivery'
    | '/login'
    | '/shop'
    | '/vendors'
    | '/dashboard/admin'
    | '/dashboard/delivery'
    | '/dashboard/login'
    | '/dashboard/vendor'
    | '/delivery/apply'
    | '/vendors/register'
    | '/delivery/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/shop'
    | '/dashboard/admin'
    | '/dashboard/delivery'
    | '/dashboard/login'
    | '/dashboard/vendor'
    | '/delivery/apply'
    | '/vendors/register'
    | '/delivery'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/delivery'
    | '/login'
    | '/shop'
    | '/vendors'
    | '/dashboard/admin'
    | '/dashboard/delivery'
    | '/dashboard/login'
    | '/dashboard/vendor'
    | '/delivery/apply'
    | '/vendors/register'
    | '/delivery/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeliveryRoute: typeof DeliveryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  VendorsRoute: typeof VendorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/vendors/register': {
      id: '/vendors/register'
      path: '/register'
      fullPath: '/vendors/register'
      preLoaderRoute: typeof VendorsRegisterRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/delivery/apply': {
      id: '/delivery/apply'
      path: '/apply'
      fullPath: '/delivery/apply'
      preLoaderRoute: typeof DeliveryApplyRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/dashboard/vendor': {
      id: '/dashboard/vendor'
      path: '/vendor'
      fullPath: '/dashboard/vendor'
      preLoaderRoute: typeof DashboardVendorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/delivery': {
      id: '/dashboard/delivery'
      path: '/delivery'
      fullPath: '/dashboard/delivery'
      preLoaderRoute: typeof DashboardDeliveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDeliveryRoute: typeof DashboardDeliveryRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardVendorRoute: typeof DashboardVendorRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDeliveryRoute: DashboardDeliveryRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardVendorRoute: DashboardVendorRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeliveryRouteChildren {
  DeliveryApplyRoute: typeof DeliveryApplyRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryApplyRoute: DeliveryApplyRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface VendorsRouteChildren {
  VendorsRegisterRoute: typeof VendorsRegisterRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsRegisterRoute: VendorsRegisterRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeliveryRoute: DeliveryRouteWithChildren,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  VendorsRoute: VendorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
